blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='posts'),
    path('<slug:slug>', views.PostDetailView.as_view(), name='post'),
    path('preview/<slug:slug>', views.PostDetailPreview.as_view(), name='post_preview')
]

mango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
]

if settings.MAINTENANCE or settings.DEBUG:
    patterns = [
        path('admin/', admin.site.urls),
    ]

    urlpatterns.extend(patterns)

if not settings.MAINTENANCE:
    patterns = [
        path('contact/', include('contact.urls', namespace='contact')),
        path('portfolio/', include('portfolio.urls', namespace='portfolio')),
        path('blog/', include('blog.urls', namespace='blog')),
    ]

    urlpatterns.extend(patterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resume.urls', namespace='resume')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('martor/', include('martor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from easy_thumbnails.fields import ThumbnailerImageField
from core.models import Profile
from datetime import datetime
import pytz
import re


# Create your models here.
class Tag(models.Model):
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'
        ordering = ['name']

    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    class Meta:
        verbose_name = 'Subcategory'
        verbose_name_plural = 'Subcategories'

    category = models.ForeignKey(Category, blank=False, null=False, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class PostReleaseManager(models.Manager):
    def get_queryset(self):
        posts = super(PostReleaseManager, self).get_queryset().filter(published=True)
        post_ids = [p.id for p in posts if p.check_release_date()]

        return posts.filter(id__in=post_ids)


class Post(models.Model):
    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ('-publish_date', 'title', 'subtitle')
        unique_together = ('title', 'subtitle')

    # Post Essentials
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255, blank=True)
    featured_image = ThumbnailerImageField(blank=True, null=True, upload_to='blog/featured_images',
                                           resize_source={'size': (865, 600)})
    slug = models.SlugField(max_length=255, unique=True, null=False, blank=True)
    body = models.TextField(blank=True, null=True)

    # Presentation & SEO
    description = models.TextField(max_length=250, blank=True, null=True)
    meta_description = models.CharField(max_length=150, blank=True)

    # Status & Visibility
    publish_date = models.DateTimeField(blank=True, null=True)
    author = models.ForeignKey(Profile, on_delete=models.PROTECT, blank=True)

    PUBLIC = 'public'
    PRIVATE = 'private'
    VISIBILITY = [
        (PUBLIC, 'Public'),
        (PRIVATE, 'Private')
    ]
    visibility = models.CharField(max_length=32, choices=VISIBILITY, blank=False, null=False, default=PUBLIC)

    # Meta Information
    published = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=True)
    last_modified = models.DateTimeField(auto_now=True)

    # Content Organization
    tags = models.ManyToManyField(Tag, blank=True)
    category = models.ForeignKey(SubCategory, blank=True, null=True, on_delete=models.PROTECT)

    # Managers
    objects = models.Manager()
    released_objects = PostReleaseManager()

    def __str__(self):
        if len(self.subtitle) > 0:
            return f'{self.title} - {self.subtitle}'
        else:
            return self.title

    def check_release_date(self):
        if self.publish_date is None:
            return False
        else:
            return datetime.now(tz=pytz.UTC) >= self.publish_date.replace(tzinfo=pytz.UTC)

    def check_released(self):
        return self.check_release_date() and self.published

    def __clean_links(self, text):
        pattern = r'\[(.+?)\]\((.+?)\)'

        return re.sub(pattern, r'\1', text)

    def __truncate_paragraph(self, text):
        pattern = r'\w+[\.\!\?]+'
        sent_endings = list(re.finditer(pattern, text))

        if len(sent_endings) > 0:
            index = sent_endings[-1].span()[-1]
            text = text[:index]

        return text

    def _create_description(self, max_char_length):
        text = self.body[:2 * max_char_length]
        text = self.__clean_links(text)[:max_char_length]

        return self.__truncate_paragraph(text)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(f'{self.title} {self.subtitle}')

        if self.publish_date is not None:
            self.published = True
        else:
            self.published = False

        if not self.description:
            self.description = self._create_description(250)

        if not self.meta_description:
            self.meta_description = self._create_description(150)

        super(Post, self).save(*args, **kwargs)

blog/views.py
from django.views import generic
from .models import Post
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class PostListView(generic.ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 4
    context_object_name = 'posts'

    def get_queryset(self):
        return self.model.released_objects.all()

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)

        posts = self.get_queryset()
        context['paginate_posts'] = posts.count() > self.paginate_by

        return context


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'blog/post.html'

    def get(self, request, *args, **kwargs):
        post = self.get_object()

        if post.check_released():
            return super(PostDetailView, self).get(request, *args, **kwargs)
        else:
            raise Http404


class PostDetailPreview(LoginRequiredMixin, generic.DetailView):
    model = Post
    template_name = 'blog/post.html'

blog/templates/blog/partials/card_image.html
{% load static %}
{% load thumbnail %}

<a href="{% url 'blog:post' slug=p.slug %}">
    {% if p.featured_image %}
        <img src="{{ p.featured_image.card.url }}" class="card-img-top">
    {% else %}
        <img src="{% static 'images/default_featured_image.jpg' %}" class="card-img-top" alt="No image found!">
    {% endif %}
</a>

blog/templates/blog/partials/card_title.html
<a href="{% url 'blog:post' slug=p.slug %}">
    {% if p.subtitle %}
        <h5 class="card-title">{{ p.title }} - {{ p.subtitle }}</h5>
    {% else %}
        <h5 class="card-title">{{ p.title }}</h5>
    {% endif %}

</a>

blog/templates/blog/partials/post_card.html
{% load markdown_extras %}
{% load bleach_tags %}
{% load thumbnail %}

<div class="card h-100">
    {% include 'blog/partials/card_image.html' %}
    <div class="card-body">
        {% include 'blog/partials/card_title.html' %}
        <p class="card-text"><small class="text-muted" style="text-align:left;">{{ p.author }}</small><small
                class="text-muted" style="float:right;">{{ p.publish_date.date }}</small></p>
        <p class="card-text">{{ p.description|markdown|bleach }}</p>
    </div>
</div>

blog/templates/blog/partials/post_card_horizontal.html
{% load markdown_extras %}
{% load bleach_tags %}

<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-5">
            {% include 'blog/partials/card_image.html' %}
        </div>
        <div class="col-md-7">
            <div class="card-body">
                {% include 'blog/partials/card_title.html' %}
                <p class="card-text"><small class="text-muted" style="text-align:left;">{{ p.author }}</small><small
                        class="text-muted" style="float:right;">{{ p.publish_date.date }}</small></p>
                <p class="card-text">{{ p.description|markdown|bleach }}</p>
            </div>
        </div>
    </div>
</div>