blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='posts'),
    path('<slug:slug>', views.PostDetailView.as_view(), name='post'),
    path('preview/<slug:slug>', views.PostDetailPreview.as_view(), name='post_preview')
]

mango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
]

if settings.MAINTENANCE or settings.DEBUG:
    patterns = [
        path('admin/', admin.site.urls),
    ]

    urlpatterns.extend(patterns)

if not settings.MAINTENANCE:
    patterns = [
        path('contact/', include('contact.urls', namespace='contact')),
        path('portfolio/', include('portfolio.urls', namespace='portfolio')),
        path('blog/', include('blog.urls', namespace='blog')),
    ]

    urlpatterns.extend(patterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resume.urls', namespace='resume')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('martor/', include('martor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.ProjectsListView.as_view(), name='projects'),
    path('data-analysis/<slug:slug>', views.DataAnalysisDetailView.as_view(), name='data_analysis'),
    path('software-project/<slug:slug>', views.SoftwareProjectDetailView.as_view(), name='software_project'),

]

portfolio/models.py
from django.db import models
from datetime import date


# Create your models here.
class ProjectReleaseManager(models.Manager):
    def get_queryset(self):
        published_projects = super(ProjectReleaseManager, self).get_queryset().filter(published=True)
        project_ids = [p.id for p in published_projects if p.released()]

        return published_projects.filter(id__in=project_ids)


class Project(models.Model):
    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'
        abstract = False
        ordering = ['-date_modified']

    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True, null=False)
    url = models.URLField(max_length=255, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    description = models.TextField(max_length=250, blank=True, null=True)
    meta_description = models.CharField(max_length=150, blank=True)
    thumbnail = models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnails')
    banner = models.ImageField(blank=True, null=True, upload_to='portfolio/banners')

    SOFTWARE_PROJECT = 'software project'
    DATA_ANALYSIS = 'data analysis'
    CATEGORY = [
        (SOFTWARE_PROJECT, 'Software Project'),
        (DATA_ANALYSIS, 'Data Analysis'),
    ]
    category = models.CharField(max_length=32, choices=CATEGORY, blank=False, null=False)

    MAINTAINER = 'maintainer'
    CONTRIBUTOR = 'contributor'
    ROLE = [
        (MAINTAINER, 'Maintainer'),
        (CONTRIBUTOR, 'Contributor')
    ]
    role = models.CharField(max_length=32, choices=ROLE, blank=False, null=False, default=MAINTAINER)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    date_finished = models.DateField(blank=True, null=True)
    publish_date = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=True)

    objects = models.Manager()
    released_objects = ProjectReleaseManager()

    def __str__(self):
        return self.name

    def released(self):
        return date.today() >= self.publish_date

portfolio/views.py
from django.views import generic
from django.http import Http404
from .models import Project


# Create your views here.
class ProjectsListView(generic.ListView):
    model = Project
    paginate_by = 10
    template_name = 'portfolio/index.html'

    def get_queryset(self):
        return self.model.released_objects.all()

    def get_context_data(self, **kwargs):
        context = super(ProjectsListView, self).get_context_data(**kwargs)

        projects = self.get_queryset()

        context['data_analyses'] = projects.filter(category='data analysis')
        context['software_projects'] = projects.filter(category='software project')

        return context


class ProjectDetailView(generic.DetailView):
    model = Project

    def get(self, request, *args, **kwargs):
        project = self.get_object()

        if project.published and project.released():
            return super(ProjectDetailView, self).get(request, *args, **kwargs)
        else:
            raise Http404


class DataAnalysisDetailView(ProjectDetailView):
    template_name = 'portfolio/data_analysis.html'


class SoftwareProjectDetailView(ProjectDetailView):
    template_name = 'portfolio/software_project.html'

portfolio/templates/portfolio/partials/data_analysis_card.html
{% load markdown_extras %}
{% load bleach_tags %}

<div class="portfolioCard">
    <div class="row g-4 align-items-center">
        <div class="col-md-auto">
            <div class="portfolioImgCol">
                <a href="{% url 'portfolio:data_analysis' slug=p.slug %}"><img
                        src="{{ p.thumbnail.url }}"
                        alt="..."></a>
            </div>
        </div>
        <div class="col-md">
            <div class="portfolioContentCol">
                <h4 class="lgTitle"><a
                        href="{% url 'portfolio:data_analysis' slug=p.slug %}">{{ p.name }}</a>
                </h4>
                <ul class="portfolioOption">
                    <li>
                                <span class="dateLbl">
                                    {{ p.publish_date }}
                                </span>
                    </li>
                </ul>
                <p>
                    {% if p.description %}
                        {{ p.description|markdown|bleach }}
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
</div>

portfolio/templates/portfolio/partials/software_project_card.html
{% load markdown_extras %}
{% load bleach_tags %}

<div class="portfolioCard">
    <div class="row g-4 align-items-center">
        <div class="col-md-auto">
            <div class="portfolioImgCol">
                <a href="{% url 'portfolio:software_project' slug=p.slug %}"><img
                        src="{{ p.thumbnail.url }}"
                        alt="..."></a>
            </div>
        </div>
        <div class="col-md">
            <div class="portfolioContentCol">
                <h4 class="lgTitle"><a
                        href="{% url 'portfolio:software_project' slug=p.slug %}">{{ p.name }}</a>
                </h4>
                <ul class="portfolioOption">
                    <li>
                                <span class="dateLbl">
                                    {{ p.date_created|date:"M. Y" }} -
                                    {% if p.date_finished %}
                                        {{ p.date_finished|date:"M. Y" }}
                                    {% else %}
                                        today
                                    {% endif %}
                                </span>
                    </li>
                </ul>
                <p>
                    {% if p.description %}
                        {{ p.description|markdown|bleach }}
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
</div>