blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='posts'),
    path('<slug:slug>', views.PostDetailView.as_view(), name='post'),
    path('preview/<slug:slug>', views.PostDetailPreview.as_view(), name='post_preview')
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.ContactView.as_view(), name='contact_page'),

]

core/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'core'

if settings.MAINTENANCE:
    if settings.LAUNCHED:
        indexView = views.MaintenanceView
    else:
        indexView = views.SoonView
else:
    indexView = views.ResumeView

urlpatterns = [
    path('', indexView.as_view(), name='home'),
    path('technical-skills/<slug:slug>', views.TechnicalSkillView.as_view(), name='technical_skill'),
    path('certificates', views.CertificatesView.as_view(), name='certificates'),
]

mango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
]

if settings.MAINTENANCE or settings.DEBUG:
    patterns = [
        path('admin/', admin.site.urls),
    ]

    urlpatterns.extend(patterns)

if not settings.MAINTENANCE:
    patterns = [
        path('contact/', include('contact.urls', namespace='contact')),
        path('portfolio/', include('portfolio.urls', namespace='portfolio')),
        path('blog/', include('blog.urls', namespace='blog')),
    ]

    urlpatterns.extend(patterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resume.urls', namespace='resume')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('martor/', include('martor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/templates/resume/index.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}Lazy Data Scientist - Home{% endblock %}
{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
End SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
End CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
End script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
    <section>
        <div class="bannerSection">
            <div class="container">
                <div class="row g-4 g-md-3  align-items-center">
                    <div class="col-md-auto order-md-last">
                        <div class="bannerUserImg">
                            <img src="{{ me.profile.avatar.url }}" alt="...">
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="bannerContent">
                            <h1 class="xlTitle pb-3">Hi, I’m {{ me.first_name|title }}, <br>
                                a {{ me.profile.profile.job_title }}</h1>
                            <p>{{ me.profile.bio }}</p>
                            <div class="bannerBtnCol">
                                <div class="row">
                                    <div class="col-auto">
                                        <a download href="{{ me.profile.profile.cv.url }}" class="btn btnPrimary">Download
                                            CV</a>
                                    </div>
                                    <div class="col-auto">
                                        <a href="{% url 'contact:contact_page' %}" class="btn btnOutline">Contact</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="sectionSpace pt-0">
            <div class="container">
                <div class="row">
                    <div class="col-md-auto">
                        <div class="softSkillCol">
                            <h4 class="smTitle pb-3">Soft Skills</h4>
                            {% for sk in me.profile.profile.soft_skills.all %}
                                {% include 'resume/partials/soft_skill.html' %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md">
                        <h4 class="smTitle pb-3">Technical Skills</h4>
                        <div class="progressCol">
                            <div class="progressCard">
                                {% for sk in me.profile.profile.technical_skills.all %}
                                    {% include 'resume/partials/technical_skill.html' %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="sectionSpaceSm lightBg">
            <div class="container">
                <div class="row pb-3">
                    <div class="col">
                        <h4 class="smText regular">Certificates</h4>
                    </div>
                    <div class="col-auto">
                        <a href="{% url 'resume:certificates' %}" class="simpleLink">View all</a>
                    </div>
                </div>
                <div class="sliderOuter">
                    <div class="swiper certificatesSlider">
                        <div class="swiper-wrapper">
                            {% for c in certificates %}
                                <div class="swiper-slide">
                                    {% include 'resume/partials/certificate_card.html' %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
                    <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
                    <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
                </div>

            </div>
        </div>
    </section>

    <section>
        <div class="sectionSpace">
            <div class="container">
                {% include 'resume/partials/portfolio.html' %}
                {% include 'resume/partials/testimonials.html' %}
            </div>
        </div>
    </section>

    <section>
        <div class="sectionSpaceSm lightBg">
            <div class="container">
                <div class="row pb-3">
                    <div class="col">
                        <h4 class="smText regular">Recent posts</h4>
                    </div>
                    <div class="col-auto">
                        <a href="{% url 'blog:posts' %}" class="simpleLink">View all</a>
                    </div>
                </div>
                <div class="sliderOuter">
                    <div class="swiper certificatesSlider">
                        <div class="swiper-wrapper">
                            {% for p in posts %}
                                <div class="swiper-slide">
                                    {% include 'blog/partials/post_card.html' %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
                    <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
                    <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
                </div>
            </div>
        </div>
        </div>
    </section>
{% endblock %}
<!-- ================================
End Content
================================= -->