blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='posts'),
    path('<slug:slug>', views.PostDetailView.as_view(), name='post'),
    path('preview/<slug:slug>', views.PostDetailPreview.as_view(), name='post_preview')
]

core/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'core'

if settings.MAINTENANCE:
    if settings.LAUNCHED:
        indexView = views.MaintenanceView
    else:
        indexView = views.SoonView
else:
    indexView = views.ResumeView

urlpatterns = [
    path('', indexView.as_view(), name='home'),
    path('technical-skills/<slug:slug>', views.TechnicalSkillView.as_view(), name='technical_skill'),
    path('certificates', views.CertificatesView.as_view(), name='certificates'),
]

mango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
]

if settings.MAINTENANCE or settings.DEBUG:
    patterns = [
        path('admin/', admin.site.urls),
    ]

    urlpatterns.extend(patterns)

if not settings.MAINTENANCE:
    patterns = [
        path('contact/', include('contact.urls', namespace='contact')),
        path('portfolio/', include('portfolio.urls', namespace='portfolio')),
        path('blog/', include('blog.urls', namespace='blog')),
    ]

    urlpatterns.extend(patterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resume.urls', namespace='resume')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('martor/', include('martor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/templates/resume/partials/technical_skill.html
<div class="progressCol">
    <a href="{% url 'resume:technical_skill' slug=sk.slug %}">
        <span class="progressLbl">{{ sk.name }}</span>
    </a>
    <div class="row g-2 align-items-center">
        <div class="col">
            <div class="progress progressStyle">
                <div class="progress-bar" role="progressbar"
                     style="width: {{ sk.score }}%"
                     aria-valuenow="{{ sk.score }}" aria-valuemin="0"
                     aria-valuemax="100"></div>
            </div>
        </div>
        <div class="col-auto">
            <span class="pLbl">{{ sk.score }}%</span>
        </div>
    </div>
</div>